CREATE TABLE quests (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        code VARCHAR(100) NOT NULL,
                        name VARCHAR(100) NOT NULL,
                        description VARCHAR(1000),

                        type VARCHAR(50) NOT NULL,
                        frequency VARCHAR(30) NOT NULL,

                        target_value BIGINT NOT NULL,

                        xp_reward BIGINT NOT NULL DEFAULT 0,
                        core_points_reward BIGINT NOT NULL DEFAULT 0,

                        enabled BOOLEAN NOT NULL DEFAULT TRUE,

                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        created_by BIGINT,
                        updated_by BIGINT,

                        CONSTRAINT uk_quests_code
                            UNIQUE (code),

                        CONSTRAINT chk_quests_type
                            CHECK (type IN (
                                            'TASK_COMPLETION_COUNT',
                                            'XP_GAINED',
                                            'CORE_POINTS_EARNED',
                                            'REWARD_REDEMPTION_COUNT'
                                )),

                        CONSTRAINT chk_quests_frequency
                            CHECK (frequency IN (
                                                 'DAILY',
                                                 'WEEKLY',
                                                 'SPECIAL'
                                )),

                        CONSTRAINT chk_quests_target_value
                            CHECK (target_value > 0),

                        CONSTRAINT chk_quests_xp_reward
                            CHECK (xp_reward >= 0),

                        CONSTRAINT chk_quests_core_points_reward
                            CHECK (core_points_reward >= 0),

                        CONSTRAINT fk_quests_created_by
                            FOREIGN KEY (created_by)
                                REFERENCES users(id)
                                ON DELETE SET NULL,

                        CONSTRAINT fk_quests_updated_by
                            FOREIGN KEY (updated_by)
                                REFERENCES users(id)
                                ON DELETE SET NULL
);

CREATE TABLE user_quests (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             fk_user_profile BIGINT NOT NULL,
                             fk_quest BIGINT NOT NULL,

                             progress_value BIGINT NOT NULL DEFAULT 0,

                             status VARCHAR(30) NOT NULL,

                             period_start DATE NOT NULL,
                             period_end DATE NOT NULL,

                             completed_at TIMESTAMP,
                             claimed_at TIMESTAMP,

                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             created_by BIGINT,
                             updated_by BIGINT,

                             CONSTRAINT uk_user_quest_period
                                 UNIQUE (
                                         fk_user_profile,
                                         fk_quest,
                                         period_start,
                                         period_end
                                     ),

                             CONSTRAINT chk_user_quests_status
                                 CHECK (status IN (
                                                   'ACTIVE',
                                                   'COMPLETED',
                                                   'CLAIMED',
                                                   'EXPIRED'
                                     )),

                             CONSTRAINT chk_user_quests_progress_value
                                 CHECK (progress_value >= 0),

                             CONSTRAINT chk_user_quests_period
                                 CHECK (period_end >= period_start),

                             CONSTRAINT fk_user_quests_user_profile
                                 FOREIGN KEY (fk_user_profile)
                                     REFERENCES user_profiles(id)
                                     ON DELETE CASCADE,

                             CONSTRAINT fk_user_quests_quest
                                 FOREIGN KEY (fk_quest)
                                     REFERENCES quests(id)
                                     ON DELETE CASCADE,

                             CONSTRAINT fk_user_quests_created_by
                                 FOREIGN KEY (created_by)
                                     REFERENCES users(id)
                                     ON DELETE SET NULL,

                             CONSTRAINT fk_user_quests_updated_by
                                 FOREIGN KEY (updated_by)
                                     REFERENCES users(id)
                                     ON DELETE SET NULL
);

CREATE INDEX idx_quests_enabled
    ON quests(enabled);

CREATE INDEX idx_quests_type
    ON quests(type);

CREATE INDEX idx_quests_frequency
    ON quests(frequency);

CREATE INDEX idx_user_quests_user_profile
    ON user_quests(fk_user_profile);

CREATE INDEX idx_user_quests_status
    ON user_quests(status);

CREATE INDEX idx_user_quests_period
    ON user_quests(period_start, period_end);