CREATE TABLE user_activity_events (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                      fk_user_profile BIGINT NOT NULL,

                                      type VARCHAR(50) NOT NULL,
                                      source_type VARCHAR(50) NOT NULL,
                                      source_id BIGINT,

                                      title VARCHAR(200) NOT NULL,
                                      description TEXT,

                                      xp_delta INTEGER NOT NULL DEFAULT 0,
                                      core_points_delta INTEGER NOT NULL DEFAULT 0,

                                      occurred_at TIMESTAMP NOT NULL,
                                      metadata_json TEXT,

                                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      created_by BIGINT,
                                      updated_by BIGINT,

                                      CONSTRAINT chk_user_activity_events_type
                                          CHECK (type IN (
                                                          'TASK_COMPLETED',
                                                          'QUEST_COMPLETED',
                                                          'QUEST_CLAIMED',
                                                          'ACHIEVEMENT_UNLOCKED',
                                                          'ACHIEVEMENT_CLAIMED',
                                                          'REWARD_REDEEMED',
                                                          'REWARD_USED',
                                                          'LEVEL_UP',
                                                          'DAILY_GOAL_QUALIFIED',
                                                          'STREAK_INCREASED',
                                                          'STREAK_BROKEN'
                                              )),

                                      CONSTRAINT chk_user_activity_events_source_type
                                          CHECK (source_type IN (
                                                                 'TASK_COMPLETION',
                                                                 'QUEST',
                                                                 'ACHIEVEMENT',
                                                                 'REWARD_REDEMPTION',
                                                                 'DAILY_PROGRESS',
                                                                 'STREAK',
                                                                 'PROGRESSION'
                                              )),

                                      CONSTRAINT fk_user_activity_events_user_profile
                                          FOREIGN KEY (fk_user_profile)
                                              REFERENCES user_profiles(id)
                                              ON DELETE CASCADE,

                                      CONSTRAINT fk_user_activity_events_created_by
                                          FOREIGN KEY (created_by)
                                              REFERENCES users(id)
                                              ON DELETE SET NULL,

                                      CONSTRAINT fk_user_activity_events_updated_by
                                          FOREIGN KEY (updated_by)
                                              REFERENCES users(id)
                                              ON DELETE SET NULL
);

CREATE INDEX idx_user_activity_events_user_profile
    ON user_activity_events(fk_user_profile);

CREATE INDEX idx_user_activity_events_type
    ON user_activity_events(type);

CREATE INDEX idx_user_activity_events_occurred_at
    ON user_activity_events(occurred_at);

CREATE INDEX idx_user_activity_events_source
    ON user_activity_events(source_type, source_id);
