CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50)  NOT NULL,
    enabled  BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE refresh_tokens
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT       NOT NULL,
    token_hash              VARCHAR(255) NOT NULL,
    created_at              TIMESTAMP    NOT NULL,
    expires_at              TIMESTAMP    NOT NULL,
    revoked                 BOOLEAN      NOT NULL DEFAULT FALSE,
    revoked_at              TIMESTAMP    NULL,
    revocation_reason       VARCHAR(50)  NULL,
    last_used_at            TIMESTAMP    NULL,
    replaced_by_token_hash  VARCHAR(64)  NULL,
    ip                      VARCHAR(128) NULL,
    user_agent              VARCHAR(512) NULL,
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX idx_refresh_tokens_revoked ON refresh_tokens (revoked);

INSERT INTO users (username, password, role, enabled)
VALUES ('admin',
        '$2a$10$WYP5.LREBkTgamnp7/xTTeLrzaRBcdNHbjs4VJ0xk/4JB9eZrPIzG',
        'ADMIN',
        TRUE) ON CONFLICT (username) DO
UPDATE
    SET password = EXCLUDED.password,
    role = EXCLUDED.role,
    enabled = EXCLUDED.enabled;

INSERT INTO users (username, password, role, enabled)
VALUES ('user',
        '$2a$10$oORx.RofsB4UbrI1hjsb6uZWs42SQoRgFxQihd4DXcDeEecmTc.IK',
        'USER',
        TRUE) ON CONFLICT (username) DO
UPDATE
    SET password = EXCLUDED.password,
    role = EXCLUDED.role,
    enabled = EXCLUDED.enabled;