-- V3__create_task_domain_tables.sql

CREATE TABLE user_profiles
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL,
    display_name        VARCHAR(120) NOT NULL,
    daily_task_goal     INT         NOT NULL DEFAULT 3,
    total_xp            BIGINT      NOT NULL DEFAULT 0,
    core_points         BIGINT      NOT NULL DEFAULT 0,
    current_streak      INT         NOT NULL DEFAULT 0,
    best_streak         INT         NOT NULL DEFAULT 0,
    last_evaluated_date DATE        NULL,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_user_profiles_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT chk_user_profiles_daily_task_goal CHECK (daily_task_goal >= 1),
    CONSTRAINT chk_user_profiles_total_xp CHECK (total_xp >= 0),
    CONSTRAINT chk_user_profiles_core_points CHECK (core_points >= 0),
    CONSTRAINT chk_user_profiles_current_streak CHECK (current_streak >= 0),
    CONSTRAINT chk_user_profiles_best_streak CHECK (best_streak >= 0)
);

CREATE TABLE task_templates
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_user_id              BIGINT       NULL,
    title                        VARCHAR(150) NOT NULL,
    description                  TEXT         NULL,
    category                     VARCHAR(50)  NOT NULL,
    difficulty                   VARCHAR(50)  NOT NULL,
    task_type                    VARCHAR(50)  NOT NULL,
    base_xp                      INT          NOT NULL,
    mandatory                    BOOLEAN      NOT NULL DEFAULT FALSE,
    streak_eligible              BOOLEAN      NOT NULL DEFAULT TRUE,
    repeatable                   BOOLEAN      NOT NULL DEFAULT FALSE,
    max_completions_per_day      INT          NOT NULL DEFAULT 1,
    diminishing_returns_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    due_time                     TIME         NULL,
    weekly_closing_day           INT          NULL,
    is_public                    BOOLEAN      NOT NULL DEFAULT FALSE,
    active                       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_templates_creator
        FOREIGN KEY (creator_user_id) REFERENCES users (id)
            ON DELETE SET NULL,
    CONSTRAINT chk_task_templates_base_xp CHECK (base_xp >= 0),
    CONSTRAINT chk_task_templates_max_completions CHECK (max_completions_per_day >= 1),
    CONSTRAINT chk_task_templates_weekly_closing_day CHECK (
        weekly_closing_day IS NULL OR weekly_closing_day BETWEEN 1 AND 7
        )
);

CREATE TABLE tasks
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                      BIGINT       NOT NULL,
    template_id                  BIGINT       NULL,
    title                        VARCHAR(150) NOT NULL,
    description                  TEXT         NULL,
    category                     VARCHAR(50)  NOT NULL,
    difficulty                   VARCHAR(50)  NOT NULL,
    task_type                    VARCHAR(50)  NOT NULL,
    base_xp                      INT          NOT NULL,
    mandatory                    BOOLEAN      NOT NULL DEFAULT FALSE,
    streak_eligible              BOOLEAN      NOT NULL DEFAULT TRUE,
    repeatable                   BOOLEAN      NOT NULL DEFAULT FALSE,
    max_completions_per_day      INT          NOT NULL DEFAULT 1,
    diminishing_returns_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    active                       BOOLEAN      NOT NULL DEFAULT TRUE,
    due_time                     TIME         NULL,
    weekly_closing_day           INT          NULL,
    created_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tasks_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_tasks_template
        FOREIGN KEY (template_id) REFERENCES task_templates (id)
            ON DELETE SET NULL,
    CONSTRAINT chk_tasks_base_xp CHECK (base_xp >= 0),
    CONSTRAINT chk_tasks_max_completions CHECK (max_completions_per_day >= 1),
    CONSTRAINT chk_tasks_weekly_closing_day CHECK (
        weekly_closing_day IS NULL OR weekly_closing_day BETWEEN 1 AND 7
        )
);

CREATE TABLE task_completions
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id                  BIGINT      NOT NULL,
    user_id                  BIGINT      NOT NULL,
    completed_at             TIMESTAMP   NOT NULL,
    completion_date          DATE        NOT NULL,
    completion_index_for_day INT         NOT NULL,
    counted_for_daily_goal   BOOLEAN     NOT NULL DEFAULT FALSE,
    counted_for_streak       BOOLEAN     NOT NULL DEFAULT FALSE,
    base_xp                  INT         NOT NULL,
    awarded_xp               INT         NOT NULL,
    awarded_core_points      INT         NOT NULL,
    notes                    TEXT        NULL,
    created_at               TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_completions_task
        FOREIGN KEY (task_id) REFERENCES tasks (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_task_completions_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT chk_task_completions_index CHECK (completion_index_for_day >= 1),
    CONSTRAINT chk_task_completions_base_xp CHECK (base_xp >= 0),
    CONSTRAINT chk_task_completions_awarded_xp CHECK (awarded_xp >= 0),
    CONSTRAINT chk_task_completions_awarded_core_points CHECK (awarded_core_points >= 0),
    CONSTRAINT uk_task_completions_task_date_index
        UNIQUE (task_id, completion_date, completion_index_for_day)
);

CREATE TABLE daily_progress
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    BIGINT      NOT NULL,
    progress_date              DATE        NOT NULL,
    required_task_count        INT         NOT NULL,
    completed_valid_task_count INT         NOT NULL DEFAULT 0,
    mandatory_tasks_required   INT         NOT NULL DEFAULT 0,
    mandatory_tasks_completed  INT         NOT NULL DEFAULT 0,
    day_qualified              BOOLEAN     NOT NULL DEFAULT FALSE,
    evaluated_at               TIMESTAMP   NULL,
    created_at                 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_daily_progress_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT uk_daily_progress_user_date
        UNIQUE (user_id, progress_date),
    CONSTRAINT chk_daily_progress_required CHECK (required_task_count >= 0),
    CONSTRAINT chk_daily_progress_completed CHECK (completed_valid_task_count >= 0),
    CONSTRAINT chk_daily_progress_mandatory_required CHECK (mandatory_tasks_required >= 0),
    CONSTRAINT chk_daily_progress_mandatory_completed CHECK (mandatory_tasks_completed >= 0)
);

CREATE INDEX idx_tasks_user_id ON tasks (user_id);
CREATE INDEX idx_tasks_template_id ON tasks (template_id);
CREATE INDEX idx_task_templates_creator_user_id ON task_templates (creator_user_id);
CREATE INDEX idx_task_completions_user_date ON task_completions (user_id, completion_date);
CREATE INDEX idx_task_completions_task_id ON task_completions (task_id);
CREATE INDEX idx_daily_progress_user_id ON daily_progress (user_id);