-- V5__align_task_domain_with_enums.sql
-- Alinea el dominio Task en BBDD con los enums reales de Java,
-- añade source en task_completions
-- y crea el modelo flexible de traits para tasks y task_templates.

-- =========================================================
-- TASK_TEMPLATES - ENUM CONSTRAINTS
-- =========================================================
ALTER TABLE task_templates
    ADD CONSTRAINT chk_task_templates_category_enum
        CHECK (category IN ('MIND', 'BODY', 'WORK', 'PERSONAL'));

ALTER TABLE task_templates
    ADD CONSTRAINT chk_task_templates_difficulty_enum
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD', 'EPIC'));

ALTER TABLE task_templates
    ADD CONSTRAINT chk_task_templates_task_type_enum
        CHECK (task_type IN ('DAILY', 'HABIT', 'ONE_TIME'));

-- =========================================================
-- TASKS - ENUM CONSTRAINTS
-- =========================================================
ALTER TABLE tasks
    ADD CONSTRAINT chk_tasks_category_enum
        CHECK (category IN ('MIND', 'BODY', 'WORK', 'PERSONAL'));

ALTER TABLE tasks
    ADD CONSTRAINT chk_tasks_difficulty_enum
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD', 'EPIC'));

ALTER TABLE tasks
    ADD CONSTRAINT chk_tasks_task_type_enum
        CHECK (task_type IN ('DAILY', 'HABIT', 'ONE_TIME'));

-- =========================================================
-- TASK_COMPLETIONS
-- =========================================================
ALTER TABLE task_completions
    ADD COLUMN source VARCHAR(50) NOT NULL DEFAULT 'MANUAL';

ALTER TABLE task_completions
    ADD CONSTRAINT chk_task_completions_source_enum
        CHECK (source IN ('MANUAL', 'SYSTEM'));

-- =========================================================
-- TRAITS CATALOG
-- =========================================================
CREATE TABLE traits
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255) NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT       NULL,
    updated_by    BIGINT       NULL,

    CONSTRAINT uk_traits_code UNIQUE (code),
    CONSTRAINT chk_traits_code_format
        CHECK (code = UPPER(code) AND code NOT LIKE '% %'),
    CONSTRAINT chk_traits_code_pattern
        CHECK (code ~ '^[A-Z_]+$'),
    CONSTRAINT fk_traits_created_by
        FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_traits_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_traits_created_by ON traits (created_by);
CREATE INDEX idx_traits_updated_by ON traits (updated_by);

-- =========================================================
-- TASK <-> TRAITS
-- =========================================================
CREATE TABLE task_traits
(
    task_id   BIGINT NOT NULL,
    trait_id  BIGINT NOT NULL,

    CONSTRAINT pk_task_traits PRIMARY KEY (task_id, trait_id),

    CONSTRAINT fk_task_traits_task
        FOREIGN KEY (task_id) REFERENCES tasks (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_task_traits_trait
        FOREIGN KEY (trait_id) REFERENCES traits (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_task_traits_task_id ON task_traits (task_id);
CREATE INDEX idx_task_traits_trait_id ON task_traits (trait_id);

-- =========================================================
-- TASK_TEMPLATE <-> TRAITS
-- =========================================================
CREATE TABLE task_template_traits
(
    task_template_id BIGINT NOT NULL,
    trait_id         BIGINT NOT NULL,

    CONSTRAINT pk_task_template_traits PRIMARY KEY (task_template_id, trait_id),

    CONSTRAINT fk_task_template_traits_template
        FOREIGN KEY (task_template_id) REFERENCES task_templates (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_task_template_traits_trait
        FOREIGN KEY (trait_id) REFERENCES traits (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_task_template_traits_template_id ON task_template_traits (task_template_id);
CREATE INDEX idx_task_template_traits_trait_id ON task_template_traits (trait_id);

-- =========================================================
-- SEED INICIAL DE TRAITS
-- =========================================================
INSERT INTO traits (code, name, description, active)
VALUES
    ('DISCIPLINE',   'Discipline',   'Consistency, routine and doing what must be done', TRUE),
    ('STRENGTH',     'Strength',     'Physical effort, training and resilience', TRUE),
    ('INTELLIGENCE', 'Intelligence', 'Learning, analysis, study and reflection', TRUE),
    ('ENERGY',       'Energy',       'Recovery, rest, sleep and vitality', TRUE),
    ('TECH_SKILL',   'Tech Skill',   'Technical skill, programming and professional practice', TRUE),
    ('FOCUS',        'Focus',        'Deep concentration and attention management', TRUE),
    ('CREATIVITY',   'Creativity',   'Creation, ideation and artistic expression', TRUE);