-- V7__create_reward_store_tables.sql
-- Crea el sistema de recompensas y canjes de Core Points.

-- =========================================================
-- REWARDS
-- =========================================================
CREATE TABLE rewards
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(100) NOT NULL,
    description             VARCHAR(500) NULL,

    type                    VARCHAR(30)  NOT NULL,
    category                VARCHAR(30)  NOT NULL,

    cost_core_points         BIGINT       NOT NULL,

    enabled                 BOOLEAN      NOT NULL DEFAULT TRUE,
    repeatable              BOOLEAN      NOT NULL DEFAULT TRUE,

    cooldown_days            INTEGER      NULL,
    required_level           BIGINT       NULL,
    required_current_streak  BIGINT       NULL,

    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT       NULL,
    updated_by              BIGINT       NULL,

    CONSTRAINT chk_rewards_type_enum
        CHECK (type IN ('REAL', 'VIRTUAL')),

    CONSTRAINT chk_rewards_category_enum
        CHECK (category IN ('FOOD', 'GAMING', 'REST', 'SHOPPING',
                            'ENTERTAINMENT', 'COSMETIC', 'TITLE', 'BADGE', 'OTHER')),

    CONSTRAINT chk_rewards_cost_core_points_positive
        CHECK (cost_core_points > 0),

    CONSTRAINT chk_rewards_cooldown_days_positive_or_zero
        CHECK (cooldown_days IS NULL OR cooldown_days >= 0),

    CONSTRAINT chk_rewards_required_level_positive
        CHECK (required_level IS NULL OR required_level >= 1),

    CONSTRAINT chk_rewards_required_current_streak_positive_or_zero
        CHECK (required_current_streak IS NULL OR required_current_streak >= 0),

    CONSTRAINT fk_rewards_created_by
        FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT fk_rewards_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_rewards_enabled ON rewards (enabled);
CREATE INDEX idx_rewards_type ON rewards (type);
CREATE INDEX idx_rewards_category ON rewards (category);
CREATE INDEX idx_rewards_created_by ON rewards (created_by);
CREATE INDEX idx_rewards_updated_by ON rewards (updated_by);

-- =========================================================
-- REWARD_REDEMPTIONS
-- =========================================================
CREATE TABLE reward_redemptions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fk_reward         BIGINT       NOT NULL,
    fk_user_profile   BIGINT       NOT NULL,

    status           VARCHAR(30)  NOT NULL,

    cost_paid         BIGINT       NOT NULL,

    redeemed_at       TIMESTAMP    NOT NULL,
    used_at           TIMESTAMP    NULL,
    cancelled_at      TIMESTAMP    NULL,

    notes             VARCHAR(1000) NULL,

    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        BIGINT       NULL,
    updated_by        BIGINT       NULL,

    CONSTRAINT fk_reward_redemptions_reward
        FOREIGN KEY (fk_reward) REFERENCES rewards (id),

    CONSTRAINT fk_reward_redemptions_user_profile
        FOREIGN KEY (fk_user_profile) REFERENCES user_profiles (id),

    CONSTRAINT chk_reward_redemptions_status_enum
        CHECK (status IN ('REDEEMED', 'USED', 'CANCELLED', 'EXPIRED')),

    CONSTRAINT chk_reward_redemptions_cost_paid_positive
        CHECK (cost_paid > 0),

    CONSTRAINT chk_reward_redemptions_used_at_status
        CHECK (used_at IS NULL OR status = 'USED'),

    CONSTRAINT chk_reward_redemptions_cancelled_at_status
        CHECK (cancelled_at IS NULL OR status = 'CANCELLED'),

    CONSTRAINT fk_reward_redemptions_created_by
        FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT fk_reward_redemptions_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_reward_redemptions_user_profile ON reward_redemptions (fk_user_profile);
CREATE INDEX idx_reward_redemptions_reward ON reward_redemptions (fk_reward);
CREATE INDEX idx_reward_redemptions_status ON reward_redemptions (status);
CREATE INDEX idx_reward_redemptions_redeemed_at ON reward_redemptions (redeemed_at);
CREATE INDEX idx_reward_redemptions_created_by ON reward_redemptions (created_by);
CREATE INDEX idx_reward_redemptions_updated_by ON reward_redemptions (updated_by);