CREATE TABLE achievements (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              code VARCHAR(100) NOT NULL,
                              name VARCHAR(100) NOT NULL,
                              description VARCHAR(1000),

                              type VARCHAR(50) NOT NULL,

                              target_value BIGINT NOT NULL,

                              xp_reward BIGINT NOT NULL DEFAULT 0,
                              core_points_reward BIGINT NOT NULL DEFAULT 0,

                              enabled BOOLEAN NOT NULL DEFAULT TRUE,
                              hidden BOOLEAN NOT NULL DEFAULT FALSE,

                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              created_by BIGINT,
                              updated_by BIGINT,

                              CONSTRAINT uk_achievements_code
                                  UNIQUE (code),

                              CONSTRAINT chk_achievements_target_value
                                  CHECK (target_value >= 0),

                              CONSTRAINT chk_achievements_xp_reward
                                  CHECK (xp_reward >= 0),

                              CONSTRAINT chk_achievements_core_points_reward
                                  CHECK (core_points_reward >= 0),

                              CONSTRAINT fk_achievements_created_by
                                  FOREIGN KEY (created_by)
                                      REFERENCES users(id)
                                      ON DELETE SET NULL,

                              CONSTRAINT fk_achievements_updated_by
                                  FOREIGN KEY (updated_by)
                                      REFERENCES users(id)
                                      ON DELETE SET NULL
);

CREATE TABLE user_achievements (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   fk_user_profile BIGINT NOT NULL,
                                   fk_achievement BIGINT NOT NULL,

                                   progress_value BIGINT NOT NULL DEFAULT 0,

                                   unlocked BOOLEAN NOT NULL DEFAULT FALSE,
                                   unlocked_at TIMESTAMP,

                                   claimed BOOLEAN NOT NULL DEFAULT FALSE,
                                   claimed_at TIMESTAMP,

                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   created_by BIGINT,
                                   updated_by BIGINT,

                                   CONSTRAINT uk_user_achievement
                                       UNIQUE (fk_user_profile, fk_achievement),

                                   CONSTRAINT fk_user_achievements_user_profile
                                       FOREIGN KEY (fk_user_profile)
                                           REFERENCES user_profiles(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT fk_user_achievements_achievement
                                       FOREIGN KEY (fk_achievement)
                                           REFERENCES achievements(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT fk_user_achievements_created_by
                                       FOREIGN KEY (created_by)
                                           REFERENCES users(id)
                                           ON DELETE SET NULL,

                                   CONSTRAINT fk_user_achievements_updated_by
                                       FOREIGN KEY (updated_by)
                                           REFERENCES users(id)
                                           ON DELETE SET NULL
);

CREATE INDEX idx_achievements_type
    ON achievements(type);

CREATE INDEX idx_achievements_enabled
    ON achievements(enabled);

CREATE INDEX idx_user_achievements_user_profile
    ON user_achievements(fk_user_profile);

CREATE INDEX idx_user_achievements_unlocked
    ON user_achievements(unlocked);